[package]
name = "validator_struct_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
validator = { version = "0.16.1", features = ["derive"] }
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
